RewardFunction: {
  shape: class
  __init__(self, name: str)
  __call__(self, datastore: Datastore, ts: TrafficSignal): float
  cache(self, datastore: Datastore, ts: TrafficSignal): float
}

AverageSpeedRewardFunction.shape: class
DiffWaitingTimeRewardFunction.shape: class
PressureRewardFunction.shape: class
QueueLengthRewardFunction.shape: class
MixedRewardFunction.shape: class
SharedVisionRewardFunction.shape: class
DiffQueueLengthRewardFunction.shape: class

AverageSpeedRewardFunction -> RewardFunction
DiffWaitingTimeRewardFunction -> RewardFunction
PressureRewardFunction -> RewardFunction
QueueLengthRewardFunction -> RewardFunction
MixedRewardFunction -> RewardFunction
SharedVisionRewardFunction -> RewardFunction
DiffQueueLengthRewardFunction -> RewardFunction
