config: Config {
  shape: class
}
environment: Environment {
  shape: class
}
datastore: Datastore {
  shape: class
}
traffic_signal: TrafficSignal {
  shape: class
}
agent: Agent {
  shape: class
}
observation_function: ObservationFunction {
  shape: class
}
reward_function: RewardFunction {
  shape: class
}
metrics: Metrics {
  shape: class
}


config -> environment: construct
environment -> datastore: maintain
environment -> metrics: track
environment -> traffic_signal
environment -> observation_function: compute observations
environment -> reward_function: compute rewards

environment -> agent: observe
environment -> agent: reward
environment <- agent: act
